apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3-deployment
  namespace: argocd-empv3
spec:
  selector:
    matchLabels:
      app: sai3
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sai3
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
